//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace StrandedConstants
{
	/* Let's implement the survival basics before we
   get into weapon-making and animal hunting */
	public enum Task
	{
        IDLE,
        RELAX_SIT,
        RELAX_PALMFAN,
        SCAVENGE_FOOD,
        SCAVENGE_WOOD,
        SCAVENGE_PALMS,
        START_FIRE,
        STOKE_FIRE,
        UPGRADE_SHELTER,
        EAT_FOOD
	}
}

